from langgraph.prebuilt import create_react_agent
from langchain_core.messages import SystemMessage, HumanMessage
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_groq import ChatGroq
from langgraph.checkpoint.memory import MemorySaver
from service.tools import get_tools
from dotenv import load_dotenv
import os

load_dotenv()

# We use an LLM that is robust at native tool calling
llm = ChatGroq(
    model="openai/gpt-oss-120b",
    api_key=os.getenv("GROQ_API_KEY"),
    temperature=0.2
)

# Global memory saver for chat threads
memory = MemorySaver()

def run_agent(vector_store, session_id: str, message: str = None, is_initial: bool = False):
    tools = get_tools(vector_store)

    # Prepare the system instructions
    system_prompt = """
    You are an advanced AI job assistant. Your goal is to analyze a user's resume and suggest highly relevant remote, hybrid, and on-site jobs along with their application links.
    
    Follow these steps strictly FOR INITIAL RESUME ANALYSIS:
    1. FIRST, use the 'Retrieve_Resume_Info' tool to search the resume context for the user's technical skills and experience level.
    2. SECOND, use the 'Search_Jobs' tool to find real job listings matching those exact skills. The tool will return results containing Title, Snippet, and Link.
    3. FINALLY, present a professional summary including:
       - A brief overview of their profile based on the resume.
       - A structured list of the suggested jobs found.
       
    FOR FOLLOW UP CHATS:
    - You MUST remember the previous jobs you suggested and refine them or answer the user's specific questions.
       
    CRITICAL INSTRUCTION FOR JOBS:
    - The user expects 10 to 15 job recommendations initially. 
    - For EVERY job you suggest, you MUST include the exact `Link` returned by the 'Search_Jobs' tool.
    - Format them nicely in markdown: `[Job Title at Company Name](Link)`.
    - NEVER invent, guess, or hallucinate job links. 
    """

    # Create the modern LangGraph ReAct agent
    agent_executor = create_react_agent(
        llm,
        tools,
        prompt=system_prompt,
        checkpointer=memory
    )

    try:
        config = {"configurable": {"thread_id": session_id}}
        
        # Determine the input message
        if is_initial:
            input_message = HumanMessage(content="Please analyze my resume and suggest jobs.")
        else:
            input_message = HumanMessage(content=message)

        # Invoke the graph with the message
        result = agent_executor.invoke({
            "messages": [input_message]
        }, config=config)

        # Extract final answer from the messages list
        # We look for the last AI message in the history
        ai_messages = [m for m in result["messages"] if hasattr(m, "content") and m.type == "ai"]
        if not ai_messages:
             return "### AI Agent Error\n\nNo response was generated by the AI. Please try again."

        final_message = ai_messages[-1]
        final_content = final_message.content

        if isinstance(final_content, list):
            # Extract text pieces from content blocks (common for Gemini)
            extracted_text = []
            for block in final_content:
                if isinstance(block, dict):
                    extracted_text.append(block.get("text", str(block)))
                elif hasattr(block, "text"):
                    extracted_text.append(block.text)
                else:
                    extracted_text.append(str(block))
            return "\n".join(extracted_text)
            
        return str(final_content) if final_content else "No result generated."
    except Exception as e:
        return f"### AI Agent Error\n\nWe encountered an issue.\n\n**Error Details:**\n`{str(e)}`\n\n*Please try again.*"
